[GLOBAL]
font = lucida-sans-unicode.ttf

[WEBVIEWER]
backgroundcolor = #101010
textcolor = #a4a4a4
chapterwidth = 50%%
indexwidth = 70%%
# font should be in /DATA folder
# Don't delete lucida yet, some script still aren't flexible enough
font = lucida-sans-unicode.ttf

