#:kivy 2.0
#:import ceil math.ceil
#:import Path pathlib.Path

<Spacing@BoxLayout>:
    orientation:"horizontal"
    size_hint:1, 0.1

<Button>:
    font_size:int(min([self.height / 2, self.width/ 8]))

<Label>:
    font_name:("DATA/" + app.style_file.get("GLOBAL", "font"))

<Border@Canvas>:
    Color:
        rgba:0,0,1,1
    Line:
        width:2
        rectangle:(self.x,self.y,self.width,self.height)

<Cover>:
    button:button
    anchor_x:"center"
    anchor_y:"bottom"
    size:230,330
    size_hint_y:None
    Button:
        id:button
        size:230, 330
        size_hint:None, None
        pos:self.parent.pos
















<ScraperWidget>:
    main:main
    grid_novel:grid_novel

    # Middel pannel
    icon:icon
    scroll_summary:scroll_summary
    summary:summary
    label_downloaded:label_downloaded
    label_read:label_read
    label_title:label_title
    #Buttons :
    button_download_10:button_download_10
    button_download_100:button_download_100
    button_download_all:button_download_all
    button_epub:button_epub
    button_PDF:button_PDF
    button_refresh:button_refresh
    button_web:button_web
    button_delete:button_delete
    button_add:button_add
    input_url:input_url
    input_source:input_source
    

    #Bottom pannel
    label_last:label_last
    
    AnchorLayout:
        id:main
        size:root.size
        label_last:label_last

        anchor_x:"center"

        BoxLayout:
            size_hint:1, 1
            orientation:"vertical"


            ScrollView:
                size_hint:1, 0.7
                
                
                GridLayout:
                    id:grid_novel
                    padding:[10, 10, 0, 0]
                    cols:int((self.parent.width - 10) / 240)
                    spacing:10
                    size_hint:1, None
                    height:int(10 + 340 * ceil(int(len(app.config_file.sections())) / (self.cols if self.cols else 2)))

            BoxLayout:
                orientation:"horizontal"
                size_hint:1, 0.01

            BoxLayout:
                size_hint:1, 0.29
                orientation:"horizontal"
                spacing:2

                GridLayout:
                    cols:2
                    rows:1
                    size_hint:0.6, 1
                    spacing:2

                    Button:
                        id:icon
                        size_hint:None, 1
                        width:self.parent.height/1.43
                        text:""

                    ScrollView:
                        id:scroll_summary
                        do_scroll_x:True
                        do_scroll_y:True
                        size_hint:None, None
                        size:self.parent.width - icon.width, self.parent.height

                        Label:
                            id:summary
                            size_hint:None, None
                            width:self.parent.width
                            text_size:self.width, None
                            height:self.texture_size[1]
                            font_size:int(min(self.width/10, self.parent.height/15))

                
                
                BoxLayout:
                    orientation:"vertical"
                    size_hint:0.4, 1


                    Label:
                        id:label_title
                        text_size:self.size
                        halign:"left"
                        text:""
                        size_hint:1, 0.2
                        bold:True
                        halign: 'center'
                    

                    Label:
                        id:label_downloaded
                        text_size:self.size
                        text:"downloaded :"
                        size_hint:1, 0.1
                        halign:"left"
            

                    Label:
                        id:label_read
                        text_size:self.size
                        text:"Read :"
                        size_hint:1, 0.1
                        halign:"left"




                    GridLayout:
                        cols:2
                        size_hint:1, 0.6

                        BoxLayout:
                            orientation:"vertical"
                            size_hint:0.5, 1

                            
                            Button:
                                id:button_epub
                                size_hint:1, 0.1
                                text:"Create Epub"

                            Button:
                                id:button_PDF
                                size_hint:1, 0.1
                                text:"Create PDF"

                            Button:
                                id:button_web
                                size_hint:1, 0.1
                                text:"Web Reader"
                            
                            Button:
                                id:button_delete
                                size_hint:1, 0.1
                                text:"Delete Novel"

                        BoxLayout:
                            orientation:"vertical"
                            size_hint:0.5, 1



                            Button:
                                id:button_download_10
                                size_hint:1, 0.1
                                text:"download 10"

                            Button:
                                id:button_download_100
                                size_hint:1, 0.1
                                text:"download 100"

                            Button:
                                id:button_download_all
                                size_hint:1, 0.1
                                text:"download all"
                            
                            Button:
                                id:button_refresh
                                size_hint:1, 0.1
                                text:"Refresh Infos"

            BoxLayout:
                size_hint:1, 0.05
                padding:5
                orientation:"horizontal"
                
                





                TextInput:
                    id:input_url
                    size_hint:0.4, 1
                
                Button:
                    id:button_add
                    text:"Add"
                    size_hint:0.06, 1
                    font_size:int(min([self.height/1.5, self.width/2.5]))


                Spinner:
                    id:input_source
                    size_hint:0.17, 1
                    values:('lightnovelpub', 'lightnovelpub')
                    text:self.values[0]
                    font_size:int(min([self.height/2, self.width/7]))



                BoxLayout:
                    orientation:"vertical"
                    size_hint:0.02, 1



                Label:
                    id:label_last
                    size_hint:0.35, 1
                    
                

